Implement WM_STATE in X11 GUI agent
QubesOS/qubes-gui-agent-linux pull request #121
Opened 2020-12-09 20:21 UTC by bemoody

These changes implement the WM_STATE property on the X11 AppVM side - allowing applications to identify the toplevel windows of other applications that are running in the same VM.

This is necessary for "screen sharing" of individual windows in Firefox and possibly other, similar programs: https://github.com/QubesOS/qubes-issues/issues/5789

2020-12-09 22:30 UTC, bemoody commented
V2: use the correct variable name (winid -> window), and added gpg signatures.  Sorry I accidentally pushed a broken version the first time.

On a side note, I found that trying to build this using `dpkg-buildpackage -b` fails, because it expects the variable BACKEND_VMM to be defined.  That variable presumably ought to be defined either in the project makefile or the debian/rules file.

2020-12-11 04:11 UTC, marmarek requested changes
Please rebase it (and make the PR) on master branch. When merged, I'll cherry pick it to release4.0.
Otherwise looks good.

2020-12-11 22:07 UTC, bemoody commented
Now rebased and I think I set the target branch correctly.

I haven't *tested* this on 4.1, but it ought to work. :)

2020-12-17 18:42 UTC, DemiMarie commented
@bemoody have you uploaded your key to a keyserver?  If not, the pipeline probably just needs to be retried.

2020-12-17 18:51 UTC, marmarek commented
PipelineRetry

2020-12-17 18:55 UTC, marmarek commented
(the above is about gitlab, not signature check - the key is still missing)

2020-12-17 18:56 UTC, bemoody commented
My public key ID is FBE2DC9A105D63ABCC5E679D323A63063AC869DF and it
should be on the keyservers.  Let me know if I need to upload it
anywhere in particular, or anything else I can do to verify myself. ;)

2020-12-17 19:02 UTC, bemoody commented
Oh, I used a signing subkey, so perhaps that's confusing the
verification system?  My subkey ID is
F0D84E04D8D1935EE37A14E9905D8AB782223619.

2020-12-17 20:40 UTC, DemiMarie commented
Using a subkey is considered best practice, and it should not confuse the verification scripts.  If it does, that’s a bug in the scripts.  @marmarek have the scripts been tested with a subkey?

2020-12-17 21:13 UTC, marmarek commented
> My public key ID is FBE2DC9A105D63ABCC5E679D323A63063AC869DF and it should be on the keyservers

```
$ gpg --keyserver pool.sks-keyservers.net  --recv-key FBE2DC9A105D63ABCC5E679D323A63063AC869DF
gpg: keyserver receive failed: No data
```
Which one?

2020-12-17 22:15 UTC, marmarek commented
PipelineRetry

2020-12-17 23:04 UTC, DemiMarie commented
> > My public key ID is FBE2DC9A105D63ABCC5E679D323A63063AC869DF and it should be on the keyservers
> 
> ```
> $ gpg --keyserver pool.sks-keyservers.net  --recv-key FBE2DC9A105D63ABCC5E679D323A63063AC869DF
> gpg: keyserver receive failed: No data
> ```
> 
> Which one?

```
gpg --recv-keys --keyserver=keys.openpgp.org -- FBE2DC9A105D63ABCC5E679D323A63063AC869DF
```

works.

2020-12-18 02:33 UTC, marmarek approved these changes
Thanks! It works!

2020-12-18 03:13 UTC, merged