Make PKGBUILD much less flaky and ideompotent
QubesOS/qubes-gui-agent-linux pull request #161
Opened 2022-06-26 22:43 UTC by locriacyber

Now building package for archlinux is easier than before! Just run `makepkg -s` inside `archlinux/` and you are good to go. No more `git clean` needed.

May break build system.

The newly produced packages are located in `archlinux/` beside `PKGBUILD`.

2022-06-27 03:11 UTC, marmarek requested changes
You correctly anticipated it will break automatic builds: https://gitlab.com/QubesOS/qubes-gui-agent-linux/-/jobs/2642172318

Generally I'm fine with changing it to run `makepkg` from `archlinux` dir, but it needs to be done without breaking existing packages. Probably change something in https://github.com/QubesOS/qubes-builder-archlinux/blob/master/Makefile.archlinux#L123-L124 and make the dir conditional on some new variable in `Makefile.builder` in the component (gui-agent-linux here). Call it `ARCH_MAKEPKG_IN_SUBDIR = 1`? Any better idea for the name?

2022-06-27 03:11 UTC, marmarek commented on archlinux/PKGBUILD
> +  rm $source -r || true
`rm -r` here too. And avoid `|| true` - if there is some specific error to ignore, prevent it from happening (I guess you meant `No such file or directory` here -> `if [ -e "$source" ]; then rm -r "$source"; fi`

2022-06-27 03:11 UTC, marmarek commented on archlinux/PKGBUILD
> +# If using pkg-config, you must update libpulse first.
Automatic builds (via qubes-builder-archlinux) _do_ install updates before building a package, so I'd prefer to keep it automatic (one place less to change by hand).

2022-06-28 03:07 UTC, locriacyber commented on archlinux/PKGBUILD
> +rm $srcdir/PKGBUILD-z-qubes-session.sh || true
It will still fail if the file doesn't exist

2022-06-28 03:17 UTC, marmarek commented on archlinux/PKGBUILD
> +rm $srcdir/PKGBUILD-z-qubes-session.sh || true
```shell
$ rm -f /no-such-file; echo $?
0
```

2022-06-28 03:38 UTC, locriacyber commented on archlinux/PKGBUILD
> +rm -rf pulse/pulsecore
It's not symlink. Check out the git repository. It's a directory.

2022-06-28 03:44 UTC, locriacyber commented on archlinux/PKGBUILD
> +rm $srcdir/PKGBUILD-z-qubes-session.sh || true
I removed `clean()`. It was for flaky build. Now we can use `makepkg -c` to clean after build.

2026-06-09 16:21 UTC, marmarek commented
Not relevant with builderv2 anymore.

2026-06-09 16:21 UTC, closed without merging