Switch to protocol 1.4
QubesOS/qubes-gui-agent-linux pull request #170
Opened 2022-08-13 06:08 UTC by DemiMarie

This breaks compatibility with protocol versions older than 1.4.
Therefore, it must not be merged until this some time after GUI daemon
4.1.23 reaches stable, as 4.1.22 is buggy and older versions only
support protocols 1.3 and below.

2023-02-28 13:47 UTC, marmarek commented
Can you bump it to 1.6 already? Technically 1.7 would be okay too, but IMO better do it only when gui-agent would actually use those extra messages.

2023-03-01 22:12 UTC, marmarek requested changes

2023-03-02 02:42 UTC, marmarek commented
> [Autotools modernization](https://github.com/QubesOS/qubes-gui-agent-linux/pull/170/commits/f382e0d9a96f264275a8179447a7168b09d8317e)

Debian build fails.

2023-03-03 12:03 UTC, marmarek commented
It doesn't work, Xorg gets SEGV:
```
[2023-03-02 22:40:08] Stack trace of thread 776:
[2023-03-02 22:40:08] #0  0x00007ac3d4444ba5 xf86_qubes_free_pixmap_private (dummyqbs_drv.so + 0x5ba5)
[2023-03-02 22:40:08] #1  0x00007ac3d4444e12 xf86_qubes_pixmap_remove_list_head (dummyqbs_drv.so + 0x5e12)
[2023-03-02 22:40:08] #2  0x00007ac3d33defd8 QubesReadInput (qubes_drv.so + 0x2fd8)
[2023-03-02 22:40:08] #3  0x000058a3e8fcc4a6 InputReady (Xorg + 0x1bb4a6)
[2023-03-02 22:40:08] #4  0x000058a3e8fcff42 ospoll_wait (Xorg + 0x1bef42)
[2023-03-02 22:40:08] #5  0x000058a3e8fd0060 InputThreadDoWork (Xorg + 0x1bf060)
[2023-03-02 22:40:08] #6  0x00007ac3d3af612d start_thread (libc.so.6 + 0x8b12d)
[2023-03-02 22:40:08] #7  0x00007ac3d3b77bc0 __clone3 (libc.so.6 + 0x10cbc0)
```

I'll try to get stacktrace with debug symbols, but maybe above is enough already?

2023-03-03 13:06 UTC, marmarek commented
Independently of the the crash, can we go one step further, to make gui-agent use Linux's deferred grant release less? Specifically, to free grants only after gui daemon either confirms mapping new set of grants for the window, or confirms window destroy.

2023-03-03 13:38 UTC, marmarek commented
```
#0  0x00007b1e0e541ba5 in xf86_qubes_free_pixmap_private (priv=0x0)
    at /usr/src/debug/qubes-gui-agent-4.2.2-1.4.fc37.x86_64/xf86-video-dummy/src/dummy_driver.c:927
#1  0x00007b1e0e541e12 in xf86_qubes_pixmap_remove_list_head ()
    at /usr/src/debug/qubes-gui-agent-4.2.2-1.4.fc37.x86_64/xf86-video-dummy/src/dummy_driver.c:965
#2  0x00007b1e0d4dbfd8 in process_request (pInfo=0x5a8f8fd344e0, fd=18)
    at /usr/src/debug/qubes-gui-agent-4.2.2-1.4.fc37.x86_64/xf86-input-mfndev/src/qubes.c:638
#3  QubesReadInput (pInfo=0x5a8f8fd344e0)
    at /usr/src/debug/qubes-gui-agent-4.2.2-1.4.fc37.x86_64/xf86-input-mfndev/src/qubes.c:651
#4  0x00005a8f8ecb34a6 in InputReady (fd=18, xevents=1, data=0x5a8f8fec1930)
    at ../../os/inputthread.c:180
#5  0x00005a8f8ecb6f42 in ospoll_wait (ospoll=0x5a8f8fd31f10, 
    timeout=timeout@entry=-1) at ../../os/ospoll.c:657
#6  0x00005a8f8ecb7060 in InputThreadDoWork (arg=<optimized out>)
    at ../../os/inputthread.c:369
#7  0x00007b1e0dbf312d in start_thread (arg=<optimized out>)
    at pthread_create.c:442
#8  0x00007b1e0dc74bc0 in clone3 ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

`priv=0x0` ...

2023-03-05 15:09 UTC, DemiMarie commented
Crash was due to freeing the wrong pointer.  I’ll reduce reliance on deferred freeing next.

2023-07-04 00:20 UTC, marmarek approved these changes

2023-07-04 00:21 UTC, merged