Disable box-shadow for GTK4 applications
QubesOS/qubes-gui-agent-linux pull request #179
Opened 2023-03-15 19:25 UTC by noskb

Fixes QubesOS/qubes-issues#8081

2023-03-16 01:48 UTC, noskb commented
If nothing is wrong, I would like to send a PR to R4.1 branch.

2023-04-05 04:07 UTC, DemiMarie requested changes

2023-04-14 01:27 UTC, noskb commented on appvm-scripts/usr/lib/qubes/qubes-gtk4-disable-box-shadow.sh
> +)
Appreciate your suggestion.

2023-04-14 01:29 UTC, noskb commented
Close this pull request as it is complete at #180

2023-04-14 01:29 UTC, closed without merging